#ifndef IMAGEVIEWPLUGIN_GLOBAL_H
#define IMAGEVIEWPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMAGEVIEWPLUGIN_LIBRARY)
#  define IMAGEVIEWPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define IMAGEVIEWPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGEVIEWPLUGIN_GLOBAL_H
